### PR TITLE
Support for multiline functions

### PR DESCRIPTION
**Pull request by tweekmonster**
This scans backwards from the cursor to find a function.  Please test it for a few days before merging so we can be certain that the scanning is fast enough and doesn't have obscure problems.

The scanning function isn't simple, but it tries to exit the loop as early as possible.  By default if there's a 1 line gap, it stops.  The maximum scanned lines is 50 just to be safe, but shouldn't get that far in typical source code.

I raised `max_parse_len` to `1000` because I think that's reasonable for functions that have strings in them.  It should still be fast, and less noticeable when timers are used.

### CODE REVIEW

**Comment by Shougo** [comment]
OK.  I will check it.

**Comment by tweekmonster** [comment]
@Shougo I haven't had any problems with this.  WDYT?

**Comment by Shougo** [comment]
I have tested it.
LGTM.

**Comment by tweekmonster** [comment]
Thanks!

**Pull request merged**
